topoguide/itineraires/urls.py
from django.urls import path

from . import views

app_name = 'itineraires'
urlpatterns = [
    path('',views.liste_itineraires, name = 'itineraires_liste'),
    # ex : /sorties/1/
    path('sorties/<int:itineraire_id>/', views.liste_sorties, name='sorties_liste'),
    path('sortie/<int:sortie_id>/', views.detail_sortie, name='sortie_detail'),
    path('nouvelle_sortie/', views.nouvelle_sortie, name = "sortie_new"),
    path('modif_sortie/<int:sortie_id>/', views.modif_sortie, name = "sortie_update"),
    
]

topoguide/topoguide/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls'), name='accounts'),
    path('',include('itineraires.urls')),
]

topoguide/itineraires/models.py
from django.db import models
from django.contrib.auth.models import User

class Itineraire(models.Model):
    """
    A hiking itinerary can have several excursions
    """
    
    CHOIX_DIFFICULTE = [
        (1,'1 - Très facile'),
        (2,'2 - Facile'),
        (3,'3 - Modérée'),
        (4,'4 - Difficile'),
        (5, '5 - Très difficile'),
    ]
    
    nom = models.CharField('Nom',max_length=200)
    p_dep = models.CharField('Point de départ',max_length=200)
    description = models.TextField('Description de la sortie')
    alt_dep = models.IntegerField('Altitude de départ')
    altitude_min = models.IntegerField('Altitude minimale')
    altitude_max = models.IntegerField('Altitude maximale')
    denivele_pos = models.IntegerField('Denivelé positif cumulé')
    denivele_neg = models.IntegerField('Denivelé negatif cumulé')
    duree = models.DurationField('Durée estimée')
    difficulte = models.IntegerField('Difficulté estimée', choices = CHOIX_DIFFICULTE)
    
    def __str__(self):
        return self.nom
class Sortie(models.Model):
    """
    An excursion has only a single user and a single itinerary
    """
    
    CHOIX_EXPERIENCE = [
        ('Tous débutants','Tous débutants'),
        ('Groupe mixte','Groupe mixte'),
        ('Tous expérimentés','Tous expérimentés'),
    ]
    
    CHOIX_METEO = [
        ('Mauvaise','Mauvaise'),
        ('Moyenne','Moyenne'),
        ('Bonne','Bonne'),
    ]
    
    CHOIX_DIFFICULTE = [
        (1,'1 - Très facile'),
        (2,'2 - Facile'),
        (3,'3 - Modérée'),
        (4,'4 - Difficile'),
        (5, '5 - Très difficile'),
    ]
    
    
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE)
    itineraire = models.ForeignKey('Itineraire', on_delete=models.CASCADE)
    date = models.DateField("Date de la sortie")
    duree_reelle = models.DurationField('Durée réelle de la sortie')
    nb_personnes = models.PositiveIntegerField('Nombre de personnes ayant participé à la sortie',default=1)
    experience = models.CharField("Experience du groupe", max_length=50 ,choices = CHOIX_EXPERIENCE)
    meteo = models.CharField(max_length=50,choices = CHOIX_METEO)
    difficulte = models.IntegerField('Difficulté ressentie', choices = CHOIX_DIFFICULTE)

topoguide/itineraires/forms.py
from django.forms import ModelForm
from itineraires.models import Sortie
from django import forms

class NewSortieForm(ModelForm):
    """
    Form made to create a new excursion
    """
    class Meta:
        model = Sortie
        fields = ['itineraire', 'date', 'duree_reelle', 'nb_personnes', 'experience', 'meteo', 'difficulte']
        labels = {
            'itineraire': 'Itinéraire',
            'date': 'Date de la sortie',
            'duree_reelle': 'Durée réelle de la sortie',
            'nb_personnes': 'Nombre de personnes',
            'experience': 'Expérience du groupe',
            'meteo': 'Météo',
            'Difficulte': 'Difficultée ressentie',
        }
        widgets = {
        'date': forms.DateInput(format=('%m/%d/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
    }

class UpdateSortieForm(ModelForm):
    """
    Same form as above but the field "itinerary" has been removed since a user 
    cannot change the itinerary corresponding to his excursion
    """
    class Meta:
        model = Sortie
        fields = ['date', 'duree_reelle', 'nb_personnes', 'experience', 'meteo', 'difficulte']
        labels = {
            'date': 'Date de la sortie',
            'duree_reelle': 'Durée réelle de la sortie',
            'nb_personnes': 'Nombre de personnes',
            'experience': 'Expérience du groupe',
            'meteo': 'Météo',
            'Difficulte': 'Difficultée ressentie',
        }
        widgets = {
        'date': forms.DateInput(format=('%m/%d/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
    }

topoguide/itineraires/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import NewSortieForm, UpdateSortieForm
from .models import Itineraire, Sortie

@login_required()
def liste_itineraires(request):
    """
    Get the list of itineraries available on the website and some of their details
    :param request: The incoming request
    """
    
    itineraries_list = Itineraire.objects.order_by("nom")
    context = {'itineraries_list' : itineraries_list }
    return render(request, 'itineraires/liste_itineraires.html', context)


@login_required()
def liste_sorties(request,itineraire_id):
    """
    Get the list of excursion corresponding to the specified itinerary
    :param request: The incoming request
    :param itineraire_id: the itinerary's ID
    """

    iti = Itineraire.objects.get(pk=itineraire_id)
    exursions_list = Sortie.objects.filter(itineraire = iti)
    context = {'excursions_list' : exursions_list, 'iti' : iti}
    return render(request,'itineraires/sorties.html',context)


@login_required()
def detail_sortie(request,sortie_id):
    """
    Get details about the specified excursion
    :param request: The incoming request
    :param sortie_id: The excursion's ID
    """
    sortie = Sortie.objects.get(pk=sortie_id)
    context = {'sortie' : sortie}
    return render(request,'itineraires/detail_sortie.html',context)


@login_required()
def nouvelle_sortie(request):
    """
    Create a new excursion based on user input in form
    
    Args:
        request: the incoming request, GET or POST
        
    Returns:
        - a page with an empty form if it was a GET request,
        - a page with an empty form if it was a POST request
          with invalid data,
        - or the list of excursions if it was a POST with valid data
    """
        
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NewSortieForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            form.instance.utilisateur = request.user
            sortie_iti = form.cleaned_data['itineraire'] # The redirection will use the itinerary id
            form.save()
            # redirect to a new URL:
            return redirect('itineraires:sorties_liste', itineraire_id = sortie_iti.id)

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NewSortieForm()

    return render(request, 'itineraires/nouvelle_sortie.html', {'form': form})


@login_required()
def modif_sortie(request, sortie_id):
    """
    Update an existing excursion based on user input in form
    
    Args:
        request: the incoming request, GET or POST
        sortie_id: the database ID of the excursion to update
        
    Returns:
        - a page with a pre-filled form if it was a GET request,
        - a page with a pre-filled form if it was a POST request
          with invalid data,
        - or the list of excursions if it was a POST with valid data
    """
    # Fist get data from the database
    sortie = Sortie.objects.get(pk=sortie_id)
    
    # The user logged-in can only edit his own excursions
    ref_user = sortie.utilisateur
    if ref_user != request.user:
        messages.error(request, ('Oups, vous ne pouvez modifier que vos propres sorties'))
        return redirect('itineraires:sorties_liste', itineraire_id = sortie.itineraire.id)
    
    # If it is a GET request we return a pre-filled form
    if request.method == 'GET':
        form = UpdateSortieForm(instance=sortie)
        
    elif request.method == 'POST':
        form = UpdateSortieForm(request.POST, instance=sortie)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            return redirect('itineraires:sorties_liste', itineraire_id = sortie.itineraire.id)
        
    return render(request,'itineraires/modif_sortie.html', {'form': form})
    
    

topoguide/itineraires/templates/base.html
{% load static %}
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
    <title>{% block title %}Topoguide{% endblock %}</title>
</head>
<style>
</style>

<body>
    <nav class="navbar navbar-success bg-success">
        <div class="container-fluid">
            
            <a class="navbar-brand text-white" href="{% url 'itineraires:itineraires_liste' %}">
                <img src="{% static 'images/hiking.png' %}" width="40" height="40" class="d-inline-block" alt="">
                Topoguide
            </a>
            <button onclick="document.location='{% url 'logout' %}'" type="button" class="btn btn-outline-light">Log out</button>
        </div>
      </nav>

    {% block content %}{% endblock %}

</body>
</html>

topoguide/itineraires/templates/itineraires/detail_sortie.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block title %}Détail d'une sortie{% endblock title%}

{% block content %}

    <h1><a class="link-success" href="{% url 'itineraires:sorties_liste' sortie.itineraire.id %}">{{ sortie.itineraire.nom }}</a> - Sortie de {{ sortie.utilisateur }}</h1>

    <p>Date : {{ sortie.date }}</p>
    <p>Durée réelle : {{ sortie.duree_reelle }}</p>
    <p>Nombre de participants : {{ sortie.nb_personnes }}</p>
    <p>Météo : {{ sortie.meteo }}</p>
    <p>Difficulté ressentie : {{ sortie.difficulte }}/5</p>

{% endblock content %}

topoguide/itineraires/templates/itineraires/liste_itineraires.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block title %}Liste des itinéraires{% endblock title%}

{% block content %}

  <h1>Itinéraires</h1>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Nom</th>
        <th scope="col">Durée estimée (hh:mm:ss)</th>
        <th scope="col">Difficulté estimée</th>
        <th scope="col">Point de départ</th>
        <th scope="col">Altitude de départ</th>
        <th scope="col">Altitude minimale</th>
        <th scope="col">Altitude maximale</th>
        <th scope="col">Dénivelé positif cumulé</th>
        <th scope="col">Dénivelé négatif cumulé</th>
      </tr>
    </thead>
    <tbody>
      {% for itinerary in itineraries_list %}
        <tr>
          <th scope="row"><a class="link-success" href="{% url 'itineraires:sorties_liste' itinerary.id %}">{{ itinerary.nom }}</a></th>
          <td>{{ itinerary.duree }}</td>
          <td>{{ itinerary.difficulte }}/5</td>
          <td>{{ itinerary.p_dep }}</td>
          <td>{{ itinerary.alt_dep }}m</td>
          <td>{{ itinerary.altitude_min }}m</td>
          <td>{{ itinerary.altitude_max }}m</td>
          <td>{{ itinerary.denivele_pos }}m</td>
          <td>{{ itinerary.denivele_neg }}m</td>
        </tr>
      {% endfor %}

    </tbody>
  </table>

 {% endblock content%}

topoguide/itineraires/templates/itineraires/modif_sortie.html
{% extends 'base.html' %}
{% load bootstrap5 %} 

{% block title %}Create New Excursion{% endblock title%}

{% block content %}

  <form action="{% url 'itineraires:sortie_update' form.instance.id %}" method="post" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
        <button type="submit" class="btn btn-success">Update</button>
        <a href="{% url 'itineraires:itineraires_liste' %}" class="btn btn-danger">Cancel</a>
  </form>

{% endblock content %}

topoguide/itineraires/templates/itineraires/nouvelle_sortie.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block title %}Ajout d'une nouvelle sortie{% endblock title%}

{% block content %}

    <h1>Nouvelle sortie</h1>


    <form action="{% url 'itineraires:sortie_new' %} " method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
            <button type="submit" class="btn btn-success">Add</button>
            <a href="{% url 'itineraires:itineraires_liste' %}" class="btn btn-danger">Cancel</a>
    </form>

{% endblock content%}

    

topoguide/itineraires/templates/itineraires/sorties.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}

{% block title %}Liste des sorties{% endblock title%}

{% block content %}

<h1> <a class="link-success" href="{% url 'itineraires:itineraires_liste' %}">{{ iti.nom }}</a></h1>


<div class="p-3 mb-2 bg-light text-dark">{{iti.description}}</div>
</p> Durée estimée : {{iti.duree}}</p>
</p> Difficulté estimé : {{iti.difficulte}}</p>
</p> Point de départ : {{iti.alt_dep}}</p>
</p> Altitude de départ : {{iti.p_dep}} </p>
</p> Altitude maximale : {{iti.alitudet_max}}</p>
</p> Altitude minimale : {{iti.altitude_min}}</p>
</p> Dénivelé positif cumulé : {{iti.denivele_pos}}</p>
</p> Dénivelé négatif cumulé  : {{iti.denivele_neg}}</p>



<h2>Sorties {{ iti.nom }}</h2>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Par</th>
            <th scope="col">Date</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    {% for excursion in excursions_list %}
    <tr>
        <th scope="row">{{ excursion.utilisateur }}</td>
        <td>{{ excursion.date }}</td>
        <td><button onclick="document.location='{% url 'itineraires:sortie_detail' excursion.id %}'" type="button" class="btn btn-outline-success">Consulter</button></td>
        <td><button onclick="document.location='{% url 'itineraires:sortie_update' excursion.id %}'" type="button" class="btn btn-outline-primary">Modifier</button></td>
    </tr>
    {% endfor %}
    
    </tbody>

    <table class="table">
    <tbody>
        <tr>
            <td></td>
            <td class="text-center"><button onclick="document.location='{% url 'itineraires:sortie_new' %}'" type="button" class="btn btn-outline-warning">+</button></td>
            <td></td>
        </tr>
    </tbody>

    {% endblock content %}